### ISSUE TITLE
What is the best way to integrate Rainbow as a NectarJS module ?

### ISSUE THREAD

**Issue by adrien-thierry** [tn0502/rainbow#521]
Hi @tido64 ,

Awesome work ! This engine is really great and easy to start with.

I would like to know what could be the best way to integrate it as a Nectar Module to be able to create cross platform video games with NectarJS ?

Thx

**Comment by tido64** [comment]
Hi @adrien-thierry, thanks for reaching out.

I found out about NectarJS a few days ago and tried to figure out how to do interop between C++ and JS but the docs seem really sparse. From looking at one of the Nectar modules, [fs](https://github.com/NectarJS/nectarjs/tree/master/nectar_modules/fs), I can see how you'd export C functions. But I would love to see more documentation around how to use [compiler/native/src/macro.h](https://github.com/NectarJS/nectarjs/blob/master/compiler/native/src/macro.h), and how to manage object lifetimes.

Another question I had was how one would bring a third-party module into Nectar. Right now everything lives under `nectar_modules`. Is the aim to have packages installed there like with npm packages?

**Comment by adrien-thierry** [comment]
Hi @tido64 , thx for your answer,

Regarding object lifetime in NectarJS, each object/array/function manages its own reference couting ptr, so when one of this type of var is out of scope with a 0 count, the memory is properly released. For null, undefined, number or string, the memory is released when the variable is out of scope

Regarding a nectar module packager, i'm adding it directly in the nectar cli, it will be availble on packages.nectarjs.com or something like this.

It's also possible to publish on NPM waiting for the package manager, as NectarJS support it.

I will improve the doc regarding how to integrate C/C++ with NectarJS. Don't hesitate to join us on Discord if you have any questions

**Comment by tido64** [comment]
> Regarding object lifetime in NectarJS, each object/array/function manages its own reference couting ptr, so when one of this type of var is out of scope with a 0 count, the memory is properly released. For null, undefined, number or string, the memory is released when the variable is out of scope

I was mostly wondering whether NectarJS has finalizers. With Duktape, you can [set a function](https://duktape.org/api.html#duk_set_finalizer) that gets called when the JS object is collected. This allows Rainbow to clean up resources on the C++ side, e.g. delete sprite batches, textures etc. Is there a similar concept in NectarJS?

> I will improve the doc regarding how to integrate C/C++ with NectarJS. Don't hesitate to join us on Discord if you have any questions

Will do. Again, thanks for reaching out. This is a very interesting project.

**Comment by adrien-thierry** [comment]
I can implement it with the Native NectarJS object, an internal __NJS_On_Destroy event that is called when the var is cleaned

You will manage it like this :

`var myNative = MyNativeFunction() // return a var with a NJS::Class::Native ptr`

Then :

`myNative["__NJS_On_Destroy"] = myCleanEvent`

**Comment by tido64** [comment]
Thanks, I've added NectarJS to the backlog: https://github.com/tido64/rainbow/projects/1#card-24165330

**Comment by adrien-thierry** [comment]
Hi,
It's now possible to add a callback to clean the Native object on delete,

I also added some native support, like struct and fixed array to improve perf
