### ISSUE TITLE
console.log ?

### ISSUE THREAD

**Issue by adrien-thierry** [tn0502/rainbow#532]
Hi, 

how to print things on a console from js ?

thx

**Comment by tido64** [comment]
Hi @adrien-thierry, `console.log` should work. Please try and let me know if it doesn't.

**Comment by adrien-thierry** [comment]
Hi, thank you for your answer,

sadly it's not working: the main window is not attached to the console : 

![console](https://user-images.githubusercontent.com/11015239/100849219-895e8d00-3482-11eb-8518-1a56bb9c6450.jpg)

**Comment by tido64** [comment]
My apologies, I was assuming you were running from Visual Studio for some reason 😛  This is indeed the "correct" behaviour with non-console apps on Windows. I can look into enabling the console. Worst case, I can redirect stdout to a file, e.g. `output.txt` or something similar. In the meantime, it looks like you can do `rainbow.exe game.js > output.txt` according to this: https://stackoverflow.com/questions/21646641/where-does-printf-write-in-a-windows-non-console-application

**Comment by adrien-thierry** [comment]
Haha don't worry ( : 

I checked with the `>` redirection, my txt file is empty

It could be perfect to have a `--console` switch to bind to the console or a new console
