### ISSUE TITLE
How to build for emscripten?

### ISSUE THREAD

**Issue by pixelblender** [tn0502/rainbow#561]
Hi,

First of all thank you for this nice framework, it has nice cross-platform features.

How do I build it for wasm? in the `build.sh` I saw a branch for emscripten but calling `../tools/build.sh emscripten` it doesn't do the build?

I'm using emsdk `sdk-releases-upstream-89202930a98fe7f9ed59b574469a9471b0bda7dd-64bit` on Linux

**Comment by tido64** [comment]
Hi @pixelblender, what error are you seeing? Did you run the command inside an activated shell as described here: https://emscripten.org/docs/getting_started/downloads.html#installation-instructions-using-the-emsdk-recommended?

**Comment by pixelblender** [comment]
Hi,

Yes I did source `emsdk_env.sh` before I ran rainbow's `build.sh`. eg:
```
$ source emsdk/emsdk_env.sh
$ cd repos/rainbow/rainbow-build/
$ ../tools/build/.sh emscripten
----------------------------------------------------------
... snip
-- Build files have been written to: repos/rainbow/rainbow-build
make: *** No targets specified and no makefile found.  Stop.
```

**Comment by tido64** [comment]
I see… Can you see whether you find a `Makefile` or a `build.ninja`? If the latter, try running `ninja` instead. I haven't built Emscripten for a while so it looks like build breaks have crept in. I will try to have a look.

Thanks for reporting this ❤️

**Comment by pixelblender** [comment]
Hi,

I managed to generate cmake by calling emcmake cmake manually. ie: `emcmake cmake -DCMAKE_TOOLCHAIN_FILE=~/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake ..` but when i try to build it I hit error:
```
repos/rainbow/src/Audio/cubeb/Mixer.h:15:10: fatal error: 'cubeb/cubeb.h' file not found
#include <cubeb/cubeb.h>
```

Using `../tools/build.sh emscripten` it does generate the `build.ninja` and if I try to build it by running `ninja` I hit the same error:
```
../src/Audio/cubeb/Mixer.h:15:10: fatal error: 'cubeb/cubeb.h' file not found
#include <cubeb/cubeb.h>
```

**Comment by tido64** [comment]
Yes, emsdk has changed a lot since I last built with it. I tried to see if I could fix it quickly here: https://github.com/tido64/rainbow/compare/tido/fix-emscripten. But I need more time to look at it. Sorry 😕

**Comment by pixelblender** [comment]
Thanks for looking into this. Awesome library! Keep up the good work! :+1:

**Comment by tido64** [comment]
@pixelblender: I've just merged a fix. Please give it a try and let me know how it goes.

(Do note that this target is still very experimental 😄)

| | |
|-|-|
| ![image](https://user-images.githubusercontent.com/4123478/111065140-7e22f080-84b8-11eb-9a01-3ccf838999ae.png) | ![image](https://user-images.githubusercontent.com/4123478/111066711-be866c80-84c0-11eb-8a5a-469038448317.png) |
