### ISSUE TITLE
logo proposal

### ISSUE THREAD

**Issue by Tobaloidee** [tn0502/rainbow#7]
Hi @tido64 , I am a graphic artist and an open source enthusiast..I passed by your project and noticed that it doesn't have a logo yet. I would like to contribute by designing one for this project if you will permit me. Thanks and best regards! - [Tobaloidee](https://steemit.com/@tobaloidee)

**Comment by tido64** [comment]
Hey @tobaloidee, we welcome any contributions. We do have a logo although it’s not featured very much. However, if we like yours more, we might use it. If that happens, we’ll give you full credit etc. 😀

**Comment by Tobaloidee** [comment]
thank you for the reply @tido64 Sir...where can i see the logo that you have already?

**Comment by tido64** [comment]
It's close to the end of [the page on transitions](https://tido64.github.io/rainbow/docs/transitions/#example).

**Comment by Tobaloidee** [comment]
I saw it just now..thanks!  I will make a draft of my design and show you here..

**Comment by Tobaloidee** [comment]
here's what i came up with...still open for suggestions
![rainbow-01](https://user-images.githubusercontent.com/36028424/54729283-acb5ab80-4bbd-11e9-8ab6-417b4825cfa6.png)

**Comment by Tobaloidee** [comment]
version 2
![rainbow ver2-02](https://user-images.githubusercontent.com/36028424/54729684-df60a380-4bbf-11e9-82a3-99da4beaa874.png)

**Comment by kalligula** [comment]
Hi @Tobaloidee ,

I think these look fantastic.

But I would really like some spicier colors (Blue, cyan and Purple/Pink) which look especially cool on a black background!

Just my 2 cents.

**Comment by Tobaloidee** [comment]
thanks for the suggestion @kalligula  will definitely do and show that version here after i edit it

**Comment by Tobaloidee** [comment]
![23rainbow-02](https://user-images.githubusercontent.com/36028424/54742891-929bbd80-4bfd-11e9-8ca9-d7d5ebee2052.png)
![23rainbow-03](https://user-images.githubusercontent.com/36028424/54742901-96c7db00-4bfd-11e9-95e2-f9f0e497ced3.png)

**Comment by tido64** [comment]
What do you think, @kalligula? I think I like version 1 in blue/pink myself.

**Comment by Tobaloidee** [comment]
just let me know which one and i will prepare the files immediately 👍

**Comment by kalligula** [comment]
Blue/Pink from me too! The non-gradient one 👍

**Comment by Tobaloidee** [comment]
Will finalize the files then ill make a PR for the logo 😃

**Comment by Tobaloidee** [comment]
here's the PR #13 with the logo upload & readme update Sirs! Thanks and best regards to the project! 
i'll share my drive link for the other file formats of the logo when i'm done with it all 💯

**Comment by tido64** [comment]
Thanks for your contribution ❤️ 

Merged #14.

**Comment by Tobaloidee** [comment]
Hi @tido64  here is the link to my drive where you can [DOWNLOAD](https://drive.google.com/drive/u/1/folders/1ja1GqAj07yRUOY2Sh0CZhidgen4J2KS5) the different versions and formats of the logo. Thanks! - Tobaloidee

**Comment by tido64** [comment]
Wow, thanks a lot ❤️
